# Generated by Django 5.2.3 on 2025-08-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_remove_job_category_delete_jobsource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
