# Generated by Django 5.2.3 on 2025-08-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_remove_job_date_posted_remove_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
