# Generated by Django 5.2.3 on 2025-08-16 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_job_application_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='application_links',
        ),
        migrations.RemoveField(
            model_name='job',
            name='link',
        ),
        migrations.RemoveField(
            model_name='job',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='source',
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('tech', 'Technology'), ('business', 'Business'), ('finance', 'Finance'), ('other', 'Other')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
